name: 'writestat'
version: 0.0.1
description: writestat
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  intl: any
  sass: '>=0.4.0 <0.5.0'
  script_inliner: '>=0.0.3 <0.1.0'
transformers:
  - script_inliner
  - sass:
      style: compressed
